---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# guerrillamail

> Guerrilla Mail gives you a disposable email address. There is no need to register, simply visit Guerrilla Mail and a random address will be given. You can also choose your own address.

> You can give your email address to whoever you do not trust. You can view the email on Guerrilla Mail, click on any confirmation link, then delete it. Any future spam sent to the disposable email will be zapped by Guerrilla Mail, never reaching your mail box, keeping your mail box safe and clean.

Taken from [Guerrilla Mail](https://www.guerrillamail.com/about).

> Guerrilla Mail provides a JSON API through HTTP. The API is public and open to all, it does not need registration or API keys to operate. The API is used by GuerrillaMail itself to power the site, so GuerrillaMail.com is actually an example for how to use the API.

Taken from the [Guerrilla Mail API Documentation](https://docs.google.com/document/d/1Qw5KQP1j57BPTDmms5nspe-QAjNEsNg8cQHpAAycYNM/edit?hl=en).

## Installation

You can install the latest version of `guerrillamail` from GitHub using

``` r
devtools::install_github("ottlngr/guerrillamail")
```

## Example
